info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 1.0.0
paths:
  /router/addr:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"查询成功"}'
          schema:
            type: string
      summary: 检测测试
      tags:
      - CheckApi
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
